name: Test en playwright

on: 
  workflow_dispatch:

jobs:
 OpenVidu_deploymen:
  name:  Run OpenVidu deployment
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: openvidu/openvidu-dev:2.23.0
          options: "-p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET"
 OpenVidu_back:
  name: Run your preferred server application sample
  runs-on: ubuntu-latest
  steps:
    - name: creación
      run: |
        ifconfig
        git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.23.0
        cd openvidu-tutorials/openvidu-basic-node
        npm install
        node index.js
        npm install --location=global http-server
 OpenVidu_client_aplication:
    name: Run the client application tutorial
    runs-on: ubuntu-latest
    steps:
      - name: iniciación
        run: |
          ifconfig
          npm install --location=global http-server
          http-server openvidu-tutorials/openvidu-js/web
      
            
