name: Test en playwright

on: 
  workflow_dispatch:

jobs:
 OpenVidu_deployment:
  name:  Run OpenVidu deployment
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: openvidu/openvidu-dev:2.23.0
          options: "-p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET"
          
 OpenVidu_back:
  name: Run your preferred server application sample
  runs-on: ubuntu-latest
  steps:
    - name: descarga
      run: git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.23.0
    - name: acceso a openvidu-basic-node
      run: |
          cd openvidu-tutorials/openvidu-basic-node
          npm install
          bg node index.js
    - name: aserver
      run: bg http-server openvidu-tutorials/openvidu-js/web
    - name: instalar playwright
      run: |
        npx playwright install --with-deps
        npx playwright test
      
        
