name: Test en playwright

on: 
  workflow_dispatch:

jobs:
 OpenVidu_deployment:
  name:  Run OpenVidu deployment
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      run: |
          docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.23.0 &
          git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.23.0
          cd openvidu-tutorials/openvidu-basic-node
          npm install
          node index.js &
          cd ..
          http-server openvidu-tutorials/openvidu-js/web &
    - name: Install playwright
      run: npm init playwright@latest
    - name: Testing 
      run: npx playwright test
    
      
