name: Test en playwright

on: 
  workflow_dispatch:

jobs:
 
 tutorial:
  name: Compile site assets
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: openvidu/openvidu-dev:2.23.0
          options: "-p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET"
          run: |
            composer install           
            git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.23.0
            cd openvidu-tutorials/openvidu-basic-node
            npm install
            node index.js
