name: Test en playwright

on: 
  push:
  workflow_dispatch:

jobs:
 OpenVidu_deployment:
  name:  Run OpenVidu deployment
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      run: |
          docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.23.0 &
    - name: Run server aplication
      run: |
          cd openvidu-basic-node
          npm install
          node index.js &
    - name: Run the client application tutorial
      run: |
          cd ..
          npm install --location=global http-server
          http-server openvidu-js/web &
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Runin Test
      run: |
         cd tests
         npx playwright test hello-world-openvidu.spec.js
 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshot.png
        path: playwright-report/screenshot.png
        retention-days: 30
   
