name: openvidu-react

on:

  push:
   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4.1.1

    - name: Run OpenVidu deployment
      run: |
        docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.29.0 > results/logs/openvidu_deployment.log 2>&1 &
        sleep 10

    - name: Run server application sample
      working-directory: openvidu-basic-node
      run: |
        npm install
        node index.js > ../results/logs/server_aplication.log 2>&1 &

    - name: Configurar Node.js
      uses: actions/setup-node@v4.0.0

    - name: Run the client application tutorial
      working-directory: openvidu-react
      run: |
        npm install
        npm start > ../results/logs/client_aplication.log 2>&1 &
  
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install
   
    - name: Install playwright-test
      run: npm install @playwright/test 
      
    - name: Runin Test
      run: |
         cd tests
         npx playwright test openvidu-react-web-tutorial.spec.js

    - uses:  actions/upload-artifact@v4
      if: always()
      with:
        name: results-react
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30
