name: openvidu-recording-node-tutorial 

on: 
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Levantar OpenVidu
      run: |
        docker run -p 4443:4443 --rm \
        -e OPENVIDU_SECRET=MY_SECRET \
        -e OPENVIDU_RECORDING=true \
        -e OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /opt/openvidu/recordings:/opt/openvidu/recordings \
        openvidu/openvidu-dev:2.28.0 > results/logs/docker_log.txt 2>&1 &
        sleep 10
    
    - uses: actions/setup-node@v3

    - name: Ejecutar la aplicación del servidor
      run: |
        git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.28.0
        cd openvidu-tutorials/openvidu-recording-node
        npm install
        node server.js http://localhost:4443 MY_SECRET > ../../results/logs/node_server_log.txt 2>&1 &
        sleep 10
        
    - name: Install dependencies
      run: npm ci
      
    - uses: browser-actions/setup-chrome@v1
    
    - name: Install Playwright Browsers
      run: npx playwright install 
      
    - name: Runin Test
      run: |
         cd tests      
         npx playwright test tests/openvidu-recording-node-tutorial.spec.js
    - name: Copy recordings
      run: |
        ls -la /openvidu/api/recordings/
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30
