name: openvidu-angular-tutorial-test 

on: 
  push:
  workflow_dispatch:

jobs:
 OpenVidu_deployment:
  name:  Run OpenVidu deployment
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Run the build process with Docker
      run: |
          sudo docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.23.0 &
          sleep 30
          cd openvidu-basic-node
          sudo npm install
          sudo node index.js &
          sleep 30
          npm -v
          npm install -g @angular/cli
          ng v
          cd ../openvidu-angular
          npm install
          ng serve
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - uses: browser-actions/setup-chrome@v1
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Runin Test
      run: |
         cd tests
         npx playwright test openvidu-js-tutorial-test.spec.js
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tests
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/tests
        retention-days: 30
