name: openvidu-iframe-tutorial 

on: 
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v4.1.1

    - name: Run OpenVidu deployment
      run: |
        docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.29.0 > results/logs/docker.log 2>&1 &
        sleep 10

    - name: Run server application sample
      working-directory: openvidu-basic-node
      run: |
        npm install
        node index.js > ../results/logs/node_index.log 2>&1 &
    
    - name: Run the client application tutorial
      run: |
          npm install --location=global http-server
          sudo http-server openvidu-hello-world/web > results/logs/http_server_helloworld.log 2>&1 &
          sleep 10 
          sudo http-server openvidu-iframe/web > results/logs/http_server_iframe.log 2>&1 &

    - name: Install dependencies
      run: npm ci
      
     
    
    - name: Install Playwright Browsers
      run: npx playwright install
    
    - name: Install playwright-test
      run: npm install @playwright/test 
      
    - name: Runin Test
      run: |
         cd tests      
         npx playwright test tests/openvidu-iframe-tutorial.spec.js

    - uses:  actions/upload-artifact@v4
      if: always()
      with:
        name: results-iframe
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30       
