name: openvidu-react


on:

  push:
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute OpenVidu Dev container
      run: docker run --detach=true -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.24.0
  
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Execute OpenVidu Tutorial Java Backend
      run:  node index.js > ../results/logs/server_application.log 2>&1 &
      working-directory: ./openvidu-basic-node
      
    - name: Execute React app in dev mode
      run: |
        npm install
        npm start &  
  
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install
   
    - name: Install playwright-test
      run: npm install @playwright/test 
      
    - name: Runing Test
      working-directory: Tests/TutorialTests
      run: |
         npx playwright test openvidu-react-web-tutorial.spec.js

    - uses:  actions/upload-artifact@v4
      if: always()
      with:
        name: results-react
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30
