name: openvidu-recording-node-tutorial 

on: 

  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4.1.1

    - name: Crear directorio recording
      run: |
        sudo mkdir -p /opt/openvidu/recordings
        sudo chmod -R a+rwx /opt/openvidu/recordings
        
    - name: Levantar OpenVidu
      run: |
        docker run -p 4443:4443 --rm \
        -e OPENVIDU_SECRET=MY_SECRET \
        -e OPENVIDU_RECORDING=true \
        -e OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /opt/openvidu/recordings:/opt/openvidu/recordings \
        openvidu/openvidu-dev:2.28.0 > results/logs/openvidu_deployment.log 2>&1 &
        sleep 10
    
    - uses: actions/setup-node@v4.0.0

    - name: Ejecutar la aplicación del servidor y de cliente
      run: |
        cd openvidu-recording-node
        sudo npm install
        sudo node server.js http://localhost:4443 MY_SECRET > ../results/logs/server_client_application.log 2>&1 &
        sleep 10
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install
    
    - name: Install playwright-test
      run: npm install @playwright/test
      
    - name: Runing Test
      working-directory: Tests/TutorialTests
      run: |      
         npx playwright test openvidu-recording-node-tutorial.spec.js
         
    - name: Copy recordings
      run: |
        cd /opt/openvidu/recordings
        sudo zip -r /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/recordings.zip .
  
    - uses:  actions/upload-artifact@v4
      if: always()
      with:
        name: results-node-tutorial
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30