name: openvidu-vue-tutorial

on:
  workflow_dispatch: {}
  push:
   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v4.1.1

    - name: Run OpenVidu deployment
      run: |
        docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.29.0 > results/logs/docker.log 2>&1 &
        sleep 10

    - name: Run server application sample
      working-directory: openvidu-basic-node
      run: |
        npm install
        node index.js > ../results/logs/node_index.log 2>&1 &

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run the client application tutorial
      working-directory: openvidu-vue
      run: |
       npm install
       npm run serve > ../results/logs/npm.log 2>&1 &
  
    - name: Install dependencies
      run: npm ci
      
    - uses: browser-actions/setup-chrome@v1
    
    - name: Install Playwright Browsers
      run: npx playwright install 
      
    - name: Runin Test
      run: |
         cd tests
         npx playwright test openvidu-vue-tutorial.spec.js

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results-react
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30
