name: openvidu-getaroom-tutorial-test 

on: 
  workflow_dispatch: {}
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Levantar OpenVidu
      run: |
        docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.28.0 &> results/logs/docker_log.txt &

    - name: Ejecutar la aplicación del servidor
      run: |
        touch results/logs/nodeindex_log.txt
        cd openvidu-basic-node
        npm install
        node index.js &> ../results/logs/nodeindex_log.txt & 
        
    - name: Levantar la aplicación cliente
      run: |
          npm install --location=global http-server
          touch results/logs/httpserver_log.txt
          http-server openvidu-getaroom/web  &> results/logs/http_server_log.txt &

    - name: Install dependencies
      run: npm ci
      
    - uses: browser-actions/setup-chrome@v1
    
    - name: Install Playwright Browsers
      run: npx playwright install 
      
    - name: Runin Test
      run: |
         cd tests
         npx playwright test openvidu-getaroom-test.spec.js
         
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30

