name: CI

on:
  push:
    branches:
      - feature-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Levantar OpenVidu
      run: |
        docker run -d -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.27.0

    - name: Ejecutar la aplicación del servidor
      run: |
        git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.27.0
        cd openvidu-tutorials/openvidu-basic-node
        npm install
        node index.js &

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Levantar la aplicación cliente
      run: |
        cd openvidu-tutorials/openvidu-react
        npm install
        npm start
