name: openvidu-recording-java-tutorial 

on: 
  workflow_dispatch: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Crear directorio recording
      run: |
        sudo mkdir -p /opt/openvidu/recordings
        sudo chmod 777 /opt/openvidu/recordings

    - name: Levantar OpenVidu
      run: |
        docker run -q -p 4443:4443 --rm \
        -e OPENVIDU_SECRET=MY_SECRET \
        -e OPENVIDU_RECORDING=true \
        -e OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /opt/openvidu/recordings:/opt/openvidu/recordings \
        openvidu/openvidu-dev:2.28.0 > results/logs/docker_log.txt 2>&1 &
        sleep 5
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11' # Puedes cambiar la versión de Java según tus necesidades
  

    - name: Ejecutar la aplicación del servidor
      run: |
        cd openvidu-tutorials/openvidu-recording-java
        mvn package exec:java > ../../results/logs/mvnpackage_log.txt 2>&1 &
        sleep 5
        
    - name: Install dependencies
      run: npm ci
      
    - uses: browser-actions/setup-chrome@v1
    
    - name: Install Playwright Browsers
      run: npx playwright install
      
    - name: Runin Test
      run: |
         cd tests      
         npx playwright test tests/openvidu-recording-java-tutorial.spec.js
         
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results
        path: /home/runner/work/openvidu-tutorials-tests-playwright/openvidu-tutorials-tests-playwright/results/
        retention-days: 30
